name: Docker Linux setup
description: Set up QEMU, Docker Buildx, and optional registry login

inputs:
  auto_push_images:
    required: false
    default: false
    description: Whether registry login is needed

  qemu_image:
    required: false
    default: tonistiigi/binfmt:qemu-v10.2.3
    description: QEMU binfmt image

  qemu_platforms:
    required: false
    default: all
    description: Platforms for QEMU

  buildkit_image:
    required: false
    default: moby/buildkit:v0.31.1
    description: BuildKit image

  docker_username:
    required: false
    default: ""
    description: Docker registry username

  docker_password:
    required: false
    default: ""
    description: Docker registry password

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      with:
        image: ${{ inputs.qemu_image }}
        platforms: ${{ inputs.qemu_platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      with:
        driver-opts: image=${{ inputs.buildkit_image }}

    - name: Login to DockerHub
      # if: ${{ inputs.auto_push_images == 'true' }}
      uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
