name: Cosign verify image
description: Verify container image signature with local Sigstore cosign private key

inputs:
  image:
    required: true
    description: Image reference in name@digest format
  identity_regexp:
    required: true
    description: Certificate identity regexp

runs:
  using: composite
  steps:
    - name: Verify image signature on Linux
      if: runner.os != 'Windows'
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        IDENTITY_REGEX: ${{ inputs.identity_regexp }}
      run: |
        set -euo pipefail

        echo "::group::Image sign data"
        echo "Identity=$IDENTITY_REGEX"
        echo "Image to verify=$IMAGE"
        echo "::endgroup::"

        echo "::group::Verify signature"
        cosign verify \
          --certificate-identity-regexp "$IDENTITY_REGEX" \
          "$IMAGE" | jq
        echo "::endgroup::"
