name: Docker metadata
description: Generate Docker tags and labels consistently

inputs:
  image:
    required: true
    description: 'Full image name, e.g. docker.io/org/prefix-image'
  os:
    required: true
    description: 'OS suffix/prefix for tags'
  event_name:
    required: true
    description: 'GitHub event name'
  version:
    required: true
    description: 'Version of the application'

outputs:
  tags:
    description: Generated Docker tags
    value: ${{ steps.meta.outputs.tags }}
  # labels:
  #   description: Generated Docker labels
  #   value: ${{ steps.meta.outputs.labels }}
  # json:
  #   description: Full metadata-action json output
  #   value: ${{ steps.meta.outputs.json }}
  # version:
  #   description: Generated version
  #   value: ${{ steps.meta.outputs.version }}

runs:
  using: composite
  steps:
    - name: Generate tags
      id: meta
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
      with:
        images: ${{ inputs.image }}
        # context: ${{ inputs.trunk_only_event == 'true' && 'git' || '' }}
        tags: |
          type=raw,enable=${{ inputs.event_name == 'workflow_dispatch' }},prefix=${{ inputs.os }}-,${{ inputs.version }}
          type=raw,enable=${{ inputs.event_name == 'workflow_dispatch' }},prefix=${{ inputs.os }}-,value=latest

