name: Attest image
description: Generate and push attestation for image

inputs:
  subject_name:
    required: true
  subject_digest:
    required: true

runs:
  using: composite
  steps:
    - name: Attest image
      uses: actions/attest@508db95dd578ae2727ebd6217d5ba78e4fbda05d # v4.2.1
      with:
        subject-name: ${{ inputs.subject_name }}
        subject-digest: ${{ inputs.subject_digest }}
        push-to-registry: true
