name: Attest image
description: Generate and push attestation for image

inputs:
  subject_name:
    required: true
  subject_digest:
    required: true

runs:
  using: composite
  steps:
    - name: Attest image
      uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
      with:
        subject-name: ${{ inputs.subject_name }}
        subject-digest: ${{ inputs.subject_digest }}
        push-to-registry: true
